version: "3"

services:
  http:
    image: service_test
    environment:
      DATABASE_URL: "postgres://tester:testing@db:5432/music?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    entrypoint: "bin/entrypoint.sh"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: testing
      POSTGRES_DB: music
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U tester -d music'"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 80s
